name: Generate ASCII Artwork

on: push

jobs:
  ASCII_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4
      - name: List repo files 
      - name: Execute Shell script to generate ASCII art
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh