name: Generate ASCII Artwork

on: push

jobs:
  ASCII_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4
      - name: Execute Shell script to generate ASCII art
        run: ./ascii-script.sh